# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc20f7c12056e42f79a37efcb2752cd3bea062e1839576cadc478d771c47318c4848b8257c68003ba3555152280ef1cbeb198a51e7498af7544723d26d6350a8

test:
  secret_key_base: 3c2d10fa78a2eae3e4697dfa860f57b3078a02e9a92ddf7e65120f910b557d7166c6da7f5d77d78d586ea9403fb73c00ae919918159babdf73cccab7e7e683ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
